#!/usr/bin/env bash
# script to config domain zone to point to load balancer
# add more subdomains and display info about them

get_record_info() {
    local domain="$1"
    local subdomain="$2"
    
    if [ -z "$subdomain" ]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        subdomains=("$subdomain")
    fi
    
    for sub in "${subdomains[@]}"; do
        result=$(dig +short "$sub.$domain")
        if [ -n "$result" ]; then
            record_type=$(dig +short -t "$sub.$domain" | awk 'NR==1{print $2}')
            echo "The subdomain $sub is a $record_type record and points to $result"
        else
            echo "The subdomain $sub does not exist."
        fi
    done
}

if [ "$#" -eq 1 ]; then
    get_record_info "$1"
elif [ "$#" -eq 2 ]; then
    get_record_info "$1" "$2"
else
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi

